{% set name = "atmcirclib" %}
{% set package = "atmcirclib" %}
{% set version = "0.7.1" %}
{% set build = "0" %}
{% set requirements = load_file_data("../requirements/requirements.yml", from_recipe_dir=True) %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  git_rev: v{{ version }}
  git_url: git+ssh://git@git.iac.ethz.ch/atmcirc/tools/atmcirclib.git

build:
  noarch: python
  number: {{ build }}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    {% for dep in requirements["dependencies"] %}
    - {{ dep.lower() }}
    {% endfor %}
  run:
    {% for dep in requirements["dependencies"] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  imports:
    - {{ package }}

about:
  license: MIT
  summary: Python library of the Atmospheric Circulation Group
  description: Python library of the Atmospheric Circulation Group
