{% set name = "atmcirclib" %}
{% set package = "atmcirclib" %}
{% set git_url = "git+ssh://git@git.iac.ethz.ch/atmcirc/tools/atmcirclib.git" %}
{% set pyproject = load_file_data("../pyproject.toml", from_recipe_dir=True) %}
{% set requirements = load_file_data("../requirements/requirements.yml", from_recipe_dir=True) %}
{% set version = pyproject["project"]["version"] %}
{% set build = "0" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  git_rev: v{{ version }}
  git_url: {{ git_url }}

build:
  noarch: python
  number: {{ build }}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    {% for dep in pyproject["build-system"]["requires"] %}
    - {{ dep.lower() }}
    {% endfor %}
    {% for dep in requirements["dependencies"] %}
    - {{ dep.lower() }}
    {% endfor %}
  run:
    {% for dep in requirements["dependencies"] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  imports:
    - {{ package }}

about:
  license: MIT
  summary: Python library of the Atmospheric Circulation Group
  description: Python library of the Atmospheric Circulation Group
