# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 815c9c2
_src_path: git@git.iac.ethz.ch:atmcirc/templates/python-project-f2py.git
author_email: stefan.ruedisuehli@env.ethz.ch
author_name: Stefan Ruedisuehli
project_description: Python library of the Atmospheric Circulation Group
project_doc_url: https://git.iac.ethz.ch/atmcirc/tools/atmcirclib
project_git_url: https://git.iac.ethz.ch/atmcirc/tools/atmcirclib
project_git_user: atmcirc
project_keywords: atmospheric circulation
project_name: AtmCircLib
project_package: atmcirclib
project_slug: atmcirclib
project_version: 0.4.0
python_version: '3.9'
year: '2022'
