# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: e81bd2e
_src_path: git@git.iac.ethz.ch:atmcirc/templates/python-project-f2py.git
author_email: stefan.ruedisuehli@env.ethz.ch
author_full_name: Stefan Ruedisuehli
git_url: https://git.iac.ethz.ch/atmcirc/tools/atmcirclib
git_user: atmcirc
project_description: Python library of the Atmospheric Circulation Group
project_keywords: atmospheric circulation
project_long_name: AtmCircLib
project_package_name: atmcirclib
project_short_name: atmcirclib
project_url: https://git.iac.ethz.ch/atmcirc/tools/atmcirclib
project_version: 0.4.0
python_requires: '>=3.9'
python_version: '3.9'
