name: atmcirclib
channels:
  - atmcirc
  - conda-forge
dependencies:
  - python>=3.9
  - pip>=22.3
  # runtime
  - atmcirc::gt4py>=2022.09.29
  - cartopy>=0.20
  - click>=8.1
  - netcdf4>=1.5
  - numpy>=1.22
  - pandas>=1.4
  - typer>=0.4
  - xarray>=2022.3
  # development
  - anaconda-client>=1.11
  - black>=22.10
  - boa>=0.14
  - codespell>=2.2
  - conda-build>=3.23
  - flake8>=6.0
  - flake8-black>=0.3
  - ipdb>=0.13
  - ipython>=8.7
  - isort>=5.11
  - mccabe>=0.7
  - mypy>=0.991
  - mamba>=1.1
  - pre-commit>=2.20
  - pydocstyle>=6.1
  - pylint>=2.15
  - pytest>=7.2
  - rich>=12.6
  - rope>=1.6
  # rstcheck>=6.1
  - sphinx>=4.3
  - sphinx-autobuild>=2021.3
  - types-toml>=0.10
  - toml>=0.10
  - types-setuptools>=65.6
  - pip:
    - copier>=7.0
    - flake8-pyproject>=1.2
    - sphinx-mdinclude>=0.5
  # f2py build tools
  - cmake>=3.22
  - ninja>=1.10
  - scikit-build>=0.14
