name: atmcirclib
channels:
  - atmcirc
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anaconda-client=1.11.0
  - anyio=3.6.2
  - appdirs=1.4.4
  - astroid=2.12.13
  - asttokens=2.2.1
  - attrs=22.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - black=22.10.0
  - boa=0.14.0
  - boltons=21.0.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cartopy=0.21.1
  - certifi=2022.12.7
  - cffi=1.15.1
  - cfgv=3.3.1
  - cftime=1.6.2
  - chardet=5.1.0
  - charset-normalizer=2.1.1
  - click=8.1.3
  - clyent=1.2.2
  - cmake=3.25.1
  - colorama=0.4.6
  - commonmark=0.9.1
  - conda=22.11.1
  - conda-build=3.23.3
  - conda-package-handling=2.0.2
  - conda-package-streaming=0.7.0
  - contourpy=1.0.6
  - cryptography=39.0.0
  - curl=7.87.0
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dataclasses=0.8
  - decorator=5.1.1
  - devtools=0.8.0
  - dill=0.3.6
  - distlib=0.3.6
  - distro=1.6.0
  - exceptiongroup=1.1.0
  - executing=0.10.0
  - expat=2.5.0
  - filelock=3.9.0
  - flake8=6.0.0
  - fmt=9.1.0
  - fonttools=4.38.0
  - freetype=2.12.1
  - future=0.18.2
  - geos=3.11.1
  - glob2=0.7
  - gt4py=2022.09.29
  - hdf4=4.2.15
  - hdf5=1.12.2
  - icu=70.1
  - identify=2.5.12
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_resources=5.10.2
  - iniconfig=1.1.1
  - ipdb=0.13.11
  - ipython=8.8.0
  - isort=5.11.4
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - json5=0.9.5
  - jsonschema=4.17.3
  - jupyter_core=5.1.2
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lazy-object-proxy=1.9.0
  - lcms2=2.14
  - ld_impl_linux-64=2.39
  - lerc=4.0.0
  - libaec=1.0.6
  - libarchive=3.6.2
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.87.0
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libgomp=12.2.0
  - libiconv=1.17
  - libjpeg-turbo=2.1.4
  - liblapack=3.9.0
  - liblief=0.12.3
  - libmamba=1.1.0
  - libmambapy=1.1.0
  - libnetcdf=4.8.1
  - libnghttp2=1.51.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsolv=0.7.23
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libtiff=4.5.0
  - libuuid=2.32.1
  - libuv=1.44.2
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.10.3
  - libzip=1.9.2
  - libzlib=1.2.13
  - lz4-c=1.9.3
  - lzo=2.10
  - make=4.3
  - mako=1.2.4
  - mamba=1.1.0
  - markupsafe=2.1.1
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - munkres=1.1.4
  - mypy=0.991
  - mypy_extensions=0.4.3
  - nbformat=5.7.1
  - ncurses=6.3
  - netcdf4=1.6.2
  - networkx=2.8.8
  - ninja=1.11.0
  - nodeenv=1.7.0
  - numpy=1.24.1
  - openjpeg=2.5.0
  - openssl=3.0.7
  - packaging=22.0
  - pandas=1.5.2
  - parso=0.8.3
  - patch=2.7.6
  - patchelf=0.17.0
  - pathspec=0.10.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=22.3.1
  - pkginfo=1.9.3
  - pkgutil-resolve-name=1.3.10
  - platformdirs=2.6.2
  - pluggy=1.0.0
  - pooch=1.6.0
  - pre-commit=2.21.0
  - proj=9.1.0
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - psutil=5.9.4
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-lief=0.12.3
  - pybind11=2.10.3
  - pybind11-abi=4
  - pybind11-global=2.10.3
  - pycodestyle=2.10.0
  - pycosat=0.6.4
  - pycparser=2.21
  - pydantic=1.10.4
  - pyflakes=3.0.1
  - pygments=2.14.0
  - pylint=2.15.9
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyproj=3.4.1
  - pyrsistent=0.19.3
  - pyshp=2.3.1
  - pysocks=1.7.1
  - pytest=7.2.0
  - python=3.11.0
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-libarchive-c=4.0
  - python-xxhash=3.2.0
  - python_abi=3.11
  - pytz=2022.7
  - pyyaml=6.0
  - readline=8.1.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.28.1
  - rhash=1.4.3
  - rich=12.6.0
  - ripgrep=13.0.0
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.7
  - scikit-build=0.16.4
  - scipy=1.10.0
  - setuptools=65.6.3
  - shapely=2.0.0
  - shellingham=1.5.0.post1
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - sqlite=3.40.0
  - stack_data=0.6.2
  - tabulate=0.9.0
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.11.6
  - toolz=0.12.0
  - tqdm=4.64.1
  - traitlets=5.8.0
  - typer=0.7.0
  - types-setuptools=65.6.0.2
  - types-toml=0.10.8.1
  - typing=3.10.0.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - typing_inspect=0.7.1
  - tzdata=2022g
  - ukkonen=1.0.1
  - urllib3=1.26.13
  - virtualenv=20.17.1
  - watchgod=0.8.2
  - wcwidth=0.2.5
  - wheel=0.38.4
  - wrapt=1.14.1
  - xarray=2022.12.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xxhash=0.8.1
  - xz=5.2.6
  - yaml=0.2.5
  - yaml-cpp=0.7.0
  - zipp=3.11.0
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.2
  - pip:
    - copier==7.0.1
    - dunamai==1.15.0
    - flake8-pyproject==1.2.2
    - iteration-utilities==0.11.0
    - jinja2-ansible-filters==1.3.2
    - plumbum==1.8.1
    - pyyaml-include==1.3
    - questionary==1.10.0
