name: atmcirclib
channels:
  - atmcirc
  - conda-forge
dependencies:
  - python>=3.9
  - pip>=22.3
  # runtime
  - atmcirc::gt4py>=2022.09.29
  - cartopy>=0.20
  - click>=8.1
  - netcdf4>=1.5
  - numpy>=1.22
  - pandas>=1.4
  - typer>=0.4
  - xarray>=2022.3
  # development
  - anaconda-client>=1.8
  - black>=22.3
  - boa>=0.14
  - conda-build>=3.21
  - flake8>=4.0
  - ipdb>=0.13
  - ipython>=8.3
  - isort>=5.10
  - mccabe>=0.6
  - mypy>=0.942
  - mamba>=0.23
  - pre-commit>=2.18
  - pylint>=2.13
  - pytest>=7.1
  - rich>=12.5
  - toml>=0.10
  - types-setuptools>=57.4
  - types-toml>=0.10
  - pip:
    - copier>=7.0
    - flake8-pyproject>=1.2
  # f2py build tools
  - cmake>=3.22
  - ninja>=1.10
  - scikit-build>=0.14
